"""Shared fixtures for the roboPID regression suite.

The goldens under tests/goldens/ were generated by generate_goldens.py on the
pre-refactor tree. Every numeric change is diffed against them, so a failure
here means behaviour moved — which is only ever acceptable deliberately.
"""

from __future__ import annotations

import pathlib
import sys

import numpy as np
import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

GOLDEN_DIR = pathlib.Path(__file__).resolve().parent / 'goldens'

# RoboPID_JPC_paper/main.tex, Section "Validation on a plant battery".
BATTERY: dict[str, tuple[list[float], float, float]] = {
    'P1': ([10.0, 1.0, 1.0, 1.0], 1.0, 1.0),      # lag-dominant
    'P2': ([5.0, 5.0, 5.0, 5.0], 1.25, 8.0),      # balanced
    'P3': ([2.0, 1.0, 1.0, 1.0], 1.0, 10.0),      # delay-dominant
    'P4': ([8.0] * 6, 1.0, 4.0),                  # high-order slow
}

# Gains used for every recorded response. GAINS_SAT is large enough to drive the
# anti-windup path hard against minu/maxu.
GAINS = (0.6, 0.05, 0.6)
GAINS_SAT = (3.0, 3.0, 3.0)

# Gains that actually settle inside the app's own horizon for each plant.
# P4 (six 8s lags + 4s of dead time) is still 13% off setpoint at 4x the
# horizon under GAINS, which pins k_delta to k2 and leaves the settling guard
# with nothing to anchor to -- see test_features.test_guard_degenerates_*.
SETTLING_GAINS = {
    'P1': GAINS,
    'P2': GAINS,
    'P3': GAINS,
    'P4': (0.3, 0.01, 0.3),
}

# Discrete outcomes -- window indices, rule branches, tuning trajectories -- are
# reproduced exactly, so they get a tight tolerance.
RTOL, ATOL = 1e-9, 1e-9

# Floating simulation output gets a looser one. dlsim and lfilter sum the same
# recursion in different orders, and the closed-loop denominators here are
# high-order and near the unit circle: P4 is degree 12, where the two differ by
# 2e-8 relative over a 521-sample record. Measured against exact rational
# arithmetic neither is systematically better (on P4, dlsim 2.3e-9 vs lfilter
# 3.6e-9; on P2 the ordering reverses) -- this is float64 noise at the
# conditioning these polynomials permit, not a behaviour difference. The bound
# below sits ~50x above the worst observed drift, which still leaves it orders
# of magnitude tighter than any real change would be.
SIM_RTOL, SIM_ATOL = 1e-6, 1e-7


@pytest.fixture(params=sorted(BATTERY), ids=sorted(BATTERY))
def plant(request):
    """(name, tau, K, L) for each battery plant."""
    name = request.param
    tau, K, L = BATTERY[name]
    return name, np.asarray(tau, dtype=float), K, L


def sim_grid(tau, L):
    """(Tsim, Ts) for a plant — the grid the app proposes for it.

    The values themselves are pinned separately in test_signals.py.
    """
    from core.signals import auto_grid
    return auto_grid(tau, L)


def golden(name: str):
    path = GOLDEN_DIR / f'{name}.npz'
    if not path.is_file():
        pytest.skip(f'golden {name}.npz missing — run tests/generate_goldens.py')
    return np.load(path)
